PrayTeam/scriptured-prayer

- scriptured-prayer-components/src/index.css
Resolves various visual oddities related to the app container, specifically on smaller resolutions.
Incorrect CSS style rules were resulting in a poor user experience caused by elements not fully expanding to fill parent heights.
Locally, via the frontend build.
Before:
After:
> fix: correct visual oddities and make styles more mobile-friendly

- manage.py
- poetry.lock
- prayerapp/dev_urls.py
- pyproject.toml
- scriptured_prayer/dev_settings.py
- scriptured_prayer/dev_urls.py
- scriptured_prayer/settings.py
- scriptured_prayer/urls.py
Development workflow should not change, but the django settings that are only for dev are in separate files. The standard config files are all for production.
I've also added the dependencies for postgres.
> feat: separate dev settings

- .github/workflows/build.yaml
- README.md
- ansible/roles/common/templates/nginx_config.j2
- ansible/roles/gunicorn/defaults/main.yaml
- ansible/roles/gunicorn/tasks/main.yaml
- ansible/roles/gunicorn/templates/gunicorn.socket.j2
- ansible/roles/postgres/tasks/main.yaml
- prayerapp/management/commands/load_cards.py
- scriptured_prayer/settings.py
Update settings and ansible to successfully deploy to fedora
CI: Run on every pull request and push, but only release on a completed merge.
CI: No longer include the staticfiles in the build. They were redundant and collecting them is one command.
Load_cards: fix the column numbers after we rearranged the spreadsheet
Django Settings: moved the staticfiles location to /var/www/html/ to separate it from gunicorn
Ansible: Made adjustments for SELinux: gunicorn is now running in httpd_t,  and there are some context adjustments that go along with that change.
Working towards automatic deployments. Manual deployments with ansible should now work.
Manually with virtual machines.
> Deploy update

- .github/workflows/build.yaml
> fix: release on merge

- ansible/roles/gunicorn/tasks/main.yaml
- ansible/roles/gunicorn/templates/nginx_config.j2
- scriptured_prayer/settings.py
> feat: ansible add option for staticroot

- .github/workflows/deploy.yaml
> ci: make ssh dir for deployment

- .github/workflows/deploy.yaml
- ansible/roles/gunicorn/tasks/main.yaml
- ansible/roles/postgres/tasks/main.yaml
- scriptured_prayer/settings.py
> Staticroot option

- .github/workflows/deploy.yaml
- ansible/roles/common/tasks/main.yaml
- ansible/roles/gunicorn/tasks/main.yaml
- ansible/roles/gunicorn/templates/env.j2
- ansible/roles/gunicorn/templates/gunicorn.service.j2
- ansible/roles/postgres/tasks/main.yaml
- ansible/roles/postgres/templates/pg_service_conf.j2
- ansible/roles/postgres/templates/pgpass.j2
- scriptured_prayer/settings.py
more deployment changes to make them more robust by using the local socket for the database and paving the way for multiple deployments on the same host with some variable changes.
Manually with ACT.
> ci: use database socket instead of port

- .github/workflows/deploy.yaml
- ansible/roles/common/tasks/main.yaml
There are 3 issues with the deployment that are fixed in this PR.
Maually with workflow_dispatch from Github.
> Fix CI Bugs

- scriptured-prayer-components/src/components/PrayerDeck.tsx
- scriptured-prayer-components/src/swiper.css
Change pagination and add navigation buttons
Change pagination type from bullets to fraction and add navigation buttons to prayer decks
gives pagination more utility by making it more readable/ Changing interface to be more desktop friendly(swiping isn't as convenient without touchscreen)
I opened a prayer deck and used the navigation buttons and the pagination updated accordingly also
- [x ] New feature (adds functionality)
- [x ] The changes I've made follow the existing code style and formatting requirements
> Swiper pagination

- .github/workflows/deploy.yaml
> ci: github3 -> github3.py

- ansible/roles/postgres/tasks/main.yaml
- frontend/src/hooks/useApi.tsx
I updated useApi to use the correct endpoint coming from Django.
I also fixed the encoding for the database in ansible.
Mostly to generate a new release.
Manually
> Fix-API-endpoint

- frontend/src/components/PrayerDeck.tsx
- prayerapp/management/commands/load_cards.py
- prayerapp/serializers.py
> Minor fixes from modeltranslation removal and fix cardApi filter

- frontend/src/App.tsx
- frontend/src/components/Footer.tsx
- frontend/src/components/FooterLink.tsx
- frontend/src/views/About.tsx
- frontend/src/views/Privacy.tsx
- frontend/src/views/Profile.tsx
- frontend/src/views/index.ts
Adds the missing important legal details.
Closes #13, #24 and #85.
To disclose legal details regarding the content and how the app is used.
Locally.
> Add privacy policy and copyright info

- prayerapp/management/commands/load_cards.py
- prayerapp/models.py
Add the utility card genre
add the instruction column to cards
backend changes for #140 
enable the request starter cards
I haven't tested it at all (famous last words)
> feat: add request starter cards

- scriptured_prayer/urls.py
> fix: space

- frontend/src/App.tsx
- frontend/src/components/Container.tsx
- frontend/src/components/ContextualNavigation.tsx
- frontend/src/components/Navigation.tsx
- frontend/src/components/NestedScreen.tsx
- frontend/src/components/PrayerDeck.tsx
- frontend/src/components/form/Input.tsx
- frontend/src/components/index.ts
- frontend/src/hooks/index.ts
- frontend/src/hooks/useScreenBreak.tsx
- frontend/src/hooks/useWindowDimensions.tsx
- frontend/src/swiper.css
- frontend/src/views/Dashboard.tsx
- frontend/src/views/Profile.tsx
In preparation for adding the [Daily Deck](#129) feature, some bugs associated with prayer decks required fixing.
Correct buggy prayer decks
Locally
> fix: correct visual bugs and requests associated with prayer decks

- frontend/src/hooks/useApi.tsx
Fix the React app improperly querying the backend, which was resulting in an HTTP 302 response.
To query the appropriate route location for the user's language.
Locally.
> fix: correct react app locale convention

- frontend/src/views/Home.tsx
Add Scriptured Prayer instructions to the homepage.
To resolve #130.
Locally.
> feat: add improved instructions on homepage

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/Navigation.tsx
- frontend/vite.config.ts
The recent changes to URLs broke some things related to navigation. This MR resolves those issues.
To correct the navigation experience.
Locally: via the React frontend using `yarn dev` and the built binary via `yarn build`.
> fix: correct issues related to navigation in conjunction with locale

- .github/workflows/build.yaml
> add poetry export plugin

- CHANGELOG.md
- pyproject.toml
> ci: fix poetry export
